apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fecrvtwfk-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/fecrvtwfk-java-springboot-gitops